### ISSUE TITLE
Fix __repr__ on Storage classes

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/modular-odm#72] opened 2013-12-18 03:21 UTC
MongoStorage::__repr__ raises TypeError:

```python
>>> print storage.MongoStorage(db, 'foo')
TypeError: __repr__ returned non-string (type Cursor)
```

**Comment by lyndsysimon** [comment] 2015-06-11 19:59
Duplicate of #112 (and fixed!)

**Closed by lyndsysimon** 2015-06-11 19:59 UTC
